# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-kernelwise"
BBFILE_PATTERN_meta-kernelwise = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-kernelwise = "10"

LAYERDEPENDS_meta-kernelwise = "core"
LAYERSERIES_COMPAT_meta-kernelwise = "kirkstone mickledore scarthgap"
